// Generated by Project X generate-all.js v0.2.0
// Core version: 3.2.6 | Profile schema: 2026-04-20
// Source profile: projectx.profile.json
export type AboutPoint = {
  icon: string;
  title: string;
  description: string;
};

export type ServiceItem = {
  icon: string;
  title: string;
  description: string;
  backgroundImage: string;
  features: string[];
};

export type PricingTier = {
  name: string;
  price: string;
  priceUnit: string;
  description: string;
  features: string[];
  cta: string;
  highlighted: boolean;
};

export type ReviewItem = {
  name: string;
  location: string;
  rating: number;
  text: string;
  avatar: string;
};

export type GalleryImage = {
  src: string;
  alt: string;
};

export type BuildMeta = {
  clientId: string;
  companyName: string;
  generatedAt: string;
  profileSchemaDate: string;
};

export const siteConfig = {
  businessName: "Colorado Commercial & Residential Painting",
  tagline: "Trusted & Value Driven for over 40 Years!",
  phone: "303-574-1740",
  phoneRaw: "13035741740",
  email: "",
  address: "Denver, CO",
  googleMapsEmbedUrl: '',
  city: "Denver",
  state: "CO",
  serviceAreaNote: "Denver metro area and surrounding Colorado communities",
  establishedYear: null,
  heroTitle: "The Best Denver Painting Contractors Since 1983!",
  heroSubtitle: "Whether you need a vibrant new color for your home’s interior or a durable exterior finish that stands up to Colorado’s weather, we have you covered.",
  heroCta: "Get a Free Quote",
  heroImageUrl: '',
  heroImageAlt: "Colorado Commercial & Residential Painting professional service",
  aboutHeadline: "Get To Know Us",
  aboutPoints: [
    {
      icon: "Calendar",
      title: "Highly rated Denver painting contractor wit…",
      description: "Highly rated Denver painting contractor with over 40 years of experience",
    },
    {
      icon: "Clock3",
      title: "Servicing both Residential and Commercial p…",
      description: "Servicing both Residential and Commercial properties",
    },
    {
      icon: "Users",
      title: "Professional service with the customer supp…",
      description: "Professional service with the customer support of a small local business",
    }
  ] as AboutPoint[],
  services: [
    {
      icon: "PaintRoller",
      title: "Residential Painting",
      description: "High-quality house painting with exceptional communication, organization, and professionalism for your biggest investment.",
      backgroundImage: "",
      features: ["Interior & exterior","Exceptional communication","Professional crew"],
    },
    {
      icon: "PaintRoller",
      title: "Commercial Painting",
      description: "Large and small commercial paint projects delivered safely within budget, on time, and with incredible value.",
      backgroundImage: "",
      features: ["Budget compliance","On-time delivery","Safety focused"],
    },
    {
      icon: "PaintRoller",
      title: "Interior Painting",
      description: "Transform your space with flawless finishes for walls, ceilings, trim, and doors using high-quality materials and precise techniques.",
      backgroundImage: "",
      features: ["Walls & ceilings","Trim & doors","Color consultation"],
    },
    {
      icon: "PaintRoller",
      title: "Exterior and Brick Painting",
      description: "Modernize your home with durable exterior finishes that withstand Denver's unpredictable weather, including brick, stucco, wood, and siding.",
      backgroundImage: "",
      features: ["Brick painting","Stucco painting","Weather-resistant finishes"],
    },
    {
      icon: "PaintRoller",
      title: "Kitchen and Cabinet Painting",
      description: "Cost-efficient cabinet refinishing that brings your kitchen back to life without the expense of replacement.",
      backgroundImage: "",
      features: ["Door removal","Sanding & prepping","Professional lasting finish"],
    },
    {
      icon: "PaintRoller",
      title: "Apartment Building Painting",
      description: "Interior and exterior painting for apartment complexes of all sizes, working around your schedule to minimize disruptions.",
      backgroundImage: "",
      features: ["Flexible scheduling","Tenant minimization","Large complex capable"],
    },
    {
      icon: "PaintRoller",
      title: "Condo Painting",
      description: "Customized condo painting solutions for individual owners, HOAs, and property managers with minimal disruption to residents.",
      backgroundImage: "",
      features: ["HOA coordination","Common area updates","Individual unit refreshes"],
    },
    {
      icon: "PaintRoller",
      title: "Multi-family Painting",
      description: "Large-scale painting for apartment complexes, condos, and townhomes using weather-resistant paints and durable coatings.",
      backgroundImage: "",
      features: ["Large-scale projects","Durable coatings","Weather-resistant"],
    }
  ] as ServiceItem[],
  pricingTiers: [

  ] as PricingTier[],
  reviews: [

  ] as ReviewItem[],
  googleReviewAvg: 5.0,
  googleReviewCount: 324,
  galleryImages: [
    {
      src: "",
      alt: "Colorado Commercial & Residential Painting Residential Painting",
    },
    {
      src: "",
      alt: "Colorado Commercial & Residential Painting Commercial Painting",
    },
    {
      src: "",
      alt: "Colorado Commercial & Residential Painting Interior Painting",
    }
  ] as GalleryImage[],
  guaranteeHeadline: "Our Service Guarantee",
  guaranteeText: "A primary focus of Colorado Commercial & Residential Painting is treating its customers with respect, integrity, and clear communication. Let us take the pain out of the painting and show you how maintaining and beautifying your home or property can be uncomplicated and worry-free.",
  guaranteePoints: ["Anytime Cancelation - Cancel at any time, for any reason before the start of the job","100% Satisfaction - We won’t accept payment until you’re fully satisfied","Warranty - We offer a warranty for all exterior and residential painting projects"],
  serviceOptions: ["Residential Painting", "Commercial Painting", "Interior Painting", "Exterior & Brick Painting", "Kitchen & Cabinet Painting", "Apartment Building Painting", "Condo Painting", "Multi-family Painting"],
  formWebhookUrl: "https://hooks.zapier.com/hooks/catch/26623925/uj1eyis/",
  formSource: "colorado-painting",
  badges: ["40+ Years Experience","5.0 Google Rating","EPA Lead Certified","No Deposits Required"],
  footerYear: new Date().getFullYear(),
  footerLinks: {
    services: ["Residential Painting", "Commercial Painting", "Interior Painting", "Exterior and Brick Painting", "Kitchen and Cabinet Painting", "Apartment Building Painting", "Condo Painting", "Multi-family Painting"],
    company: [
      { label: 'About Us', href: '#about' },
      { label: 'Our Guarantee', href: '#guarantee' },
      { label: 'Reviews', href: '#reviews' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  socialLinks: {
    facebook: "",
    instagram: "",
    google: "https://coloradopainting.com/",
  },
  buildMeta: {
    clientId: "colorado-painting",
    companyName: "Colorado Commercial & Residential Painting",
    generatedAt: "2026-04-21T17:37:47.507Z",
    profileSchemaDate: "2026-04-20",
  } as BuildMeta,
};
