// Auto-generated by projectx-render-config from client profile
// DO NOT EDIT — regenerate from profile.json instead

export interface ServiceItem {
  icon: string;
  title: string;
  description: string;
  backgroundImage?: string;
  features: string[];
}

export interface ReviewItem {
  name: string;
  location: string;
  rating: number;
  text: string;
  avatar: string;
}

export interface PricingTier {
  name: string;
  price: string;
  priceUnit: string;
  description: string;
  features: string[];
  highlighted?: boolean;
  cta?: string;
}

export interface AboutPoint {
  icon: string;
  title: string;
  description: string;
}

export interface GalleryImage {
  src: string;
  alt: string;
  caption?: string;
}

export const siteConfig = {
  businessName: 'Smoky Hill Roofing',
  tagline: 'Smoky Hill Roofing — Roof Replacement',
  phone: '(303) 944-3861',
  phoneRaw: '13039443861',
  email: 'sales@smokyhillroofing.com',
  city: 'Denver',
  state: 'CO',
  address: '900 N Sherman St',
  serviceAreaNote: 'Serving Denver and surrounding areas',
  establishedYear: 2010,
  footerYear: 2026,
  googleMapsEmbedUrl: '',

  heroTitle: 'Professional Roof Replacement in Denver',
  heroSubtitle: 'Trusted Smoky Hill Roofing serving Denver. Call today for a free estimate.',
  heroCta: 'Get a Free Estimate',
  heroImageUrl: '',
  heroImageAlt: 'Smoky Hill Roofing professional service',

  aboutHeadline: 'Why Homeowners Trust Us',
  aboutPoints: [
  {
    icon: 'ShieldCheck',
    title: 'Licensed & Insured',
    description: 'Smoky Hill Roofing is fully licensed and insured for your protection.',
  },
  {
    icon: 'Clock',
    title: 'Fast Response Times',
    description: 'We respond quickly and show up on time, every time.',
  },
  {
    icon: 'Award',
    title: 'Years of Experience',
    description: 'Serving the Denver area since 2010.',
  }
  ] as AboutPoint[],

  services: [
  {
    icon: '🏠',
    title: 'Roof Replacement',
    description: 'Complete roof replacement services for residential and commercial properties',
    features: ['Full tear-off', 'New installation', 'Material selection', 'Warranty included'],
  },
  {
    icon: '🔧',
    title: 'Roof Repair',
    description: 'Professional roof repair services for storm damage and general maintenance',
    features: ['Leak repair', 'Shingle replacement', 'Emergency service', 'Same-day estimates'],
  },
  {
    icon: '⛈️',
    title: 'Storm Damage Repair',
    description: 'Specialized storm damage assessment and repair services',
    features: ['Insurance claims assistance', 'Emergency tarping', 'Hail damage repair', 'Wind damage restoration'],
  },
  {
    icon: '🏗️',
    title: 'New Construction',
    description: 'New roof installation for residential and commercial construction projects',
    features: ['Custom design', 'Material consultation', 'Code compliance', 'Project management'],
  }
  ] as ServiceItem[],

  reviews: [

  ] as ReviewItem[],

  pricingTiers: [
  {
    name: 'Roof Replacement',
    price: 'Free Estimate',
    priceUnit: '',
    description: 'Complete roof replacement services for residential and commercial properties',
    features: ['Full tear-off', 'New installation', 'Material selection', 'Warranty included'],
    highlighted: true,
    cta: 'Get Free Estimate',
  },
  {
    name: 'Roof Repair',
    price: 'Call for Pricing',
    priceUnit: '',
    description: 'Professional roof repair services for storm damage and general maintenance',
    features: ['Leak repair', 'Shingle replacement', 'Emergency service', 'Same-day estimates'],
    highlighted: false,
    cta: 'Contact Us',
  },
  {
    name: 'Storm Damage Repair',
    price: 'Call for Pricing',
    priceUnit: '',
    description: 'Specialized storm damage assessment and repair services',
    features: ['Insurance claims assistance', 'Emergency tarping', 'Hail damage repair', 'Wind damage restoration'],
    highlighted: false,
    cta: 'Contact Us',
  }
  ] as PricingTier[],

  guaranteeHeadline: 'Our Guarantee',
  guaranteeText: 'At Smoky Hill Roofing, we stand behind every job. If you are not 100% satisfied, we will make it right.',
  guaranteePoints: [
'Quality workmanship guaranteed', 'Transparent pricing with no hidden fees', 'Friendly, professional service every time'
  ] as string[],

  galleryImages: [

  ] as GalleryImage[],

  googleReviewAvg: 4.9,
  googleReviewCount: 100,

  serviceOptions: [
'Residential roofing', 'Commercial roofing', 'Emergency repairs', 'Insurance claims'
  ] as string[],

  formWebhookUrl: 'https://hooks.zapier.com/hooks/catch/26623925/uj1eyis/',
  formSource: 'smoky-hill-roofing',

  badges: [
'Licensed & Insured', 'Free Estimates', '5-Star Rated', 'Locally Owned'
  ] as string[],

  socialLinks: {
    Google: '',
    Yelp: '',
    Facebook: ''
  } as Record<string, string>,

  footerLinks: {
    services: ['Roof Replacement', 'Roof Repair', 'Storm Damage Repair', 'New Construction'] as string[],
    company: [
    { label: 'About Us', href: '#about' },
    { label: 'Contact', href: '#contact' },
    { label: 'Privacy Policy', href: '/privacy' }
    ] as { label: string; href: string }[],
  },

  brand: {
    primary: '#32373C',
    primaryForeground: '#FFFFFF',
    accent: '#FF6900',
    accentForeground: '#0B1220',
    warmAccent: '#FCB900',
    warmAccentForeground: '#32373C',
    border: '#ABB8C3',
    canvas: '#FFFFFF',
    foreground: '#32373C',
    primaryHsl: '210 9% 22%',
    primaryForegroundHsl: '0 0% 100%',
    accentHsl: '25 100% 50%',
    accentForegroundHsl: '220 49% 8%',
    warmAccentHsl: '44 100% 49%',
    warmAccentForegroundHsl: '210 9% 22%',
    borderHsl: '207 17% 72%',
    canvasHsl: '0 0% 100%',
    foregroundHsl: '210 9% 22%',
  },
};
