// Generated by Project X generate-all.js v0.2.0
// Core version: 3.2.6 | Profile schema: 2026-04-20
// Source profile: projectx.profile.json
export type AboutPoint = {
  icon: string;
  title: string;
  description: string;
};

export type ServiceItem = {
  icon: string;
  title: string;
  description: string;
  backgroundImage: string;
  features: string[];
};

export type PricingTier = {
  name: string;
  price: string;
  priceUnit: string;
  description: string;
  features: string[];
  cta: string;
  highlighted: boolean;
};

export type ReviewItem = {
  name: string;
  location: string;
  rating: number;
  text: string;
  avatar: string;
};

export type GalleryImage = {
  src: string;
  alt: string;
};

export type BuildMeta = {
  clientId: string;
  companyName: string;
  generatedAt: string;
  profileSchemaDate: string;
};

export const siteConfig = {
  businessName: "Mister Sparky",
  tagline: "Play It Safe & Choose Mister Sparky!",
  phone: "(305) 508-4225",
  phoneRaw: "13055084225",
  email: "",
  address: "12155 SW 114th Pl Bay 22, Miami, FL, 33176",
  googleMapsEmbedUrl: '',
  city: "Miami",
  state: "FL",
  serviceAreaNote: "Serving Miami-Dade County and surrounding South Florida communities, including Coral Gables, Doral, Kendall, and Miami Beach.",
  establishedYear: null,
  heroTitle: "Electricians in Miami, FL",
  heroSubtitle: "Got flickering lights, a circuit breaker that keeps tripping, or outdated electrical panels? Mister Sparky’s electricians in Miami, FL are here to bring expert solutions and top-of-the-line equipment to ensure your home’s electrical system runs safely and smoothly.",
  heroCta: "Book Now",
  heroImageUrl: '',
  heroImageAlt: "Mister Sparky professional service",
  aboutHeadline: "Expert Local Electricians Services in Miami",
  aboutPoints: [
    {
      icon: "ShieldCheck",
      title: "Verify the safety of your electrical system",
      description: "Verify the safety of your electrical system",
    },
    {
      icon: "Clock3",
      title: "Identify any issues that currently compromi…",
      description: "Identify any issues that currently compromise your safety",
    },
    {
      icon: "Award",
      title: "Prepare you to address or prevent future el…",
      description: "Prepare you to address or prevent future electrical issues",
    },
    {
      icon: "Users",
      title: "Determine when a problem can be repaired",
      description: "Determine when a problem can be repaired",
    },
    {
      icon: "TrendingUp",
      title: "Recommend a workable option for non-repaira…",
      description: "Recommend a workable option for non-repairable electrical issues",
    }
  ] as AboutPoint[],
  services: [
    {
      icon: "Fan",
      title: "Electrical Repairs",
      description: "Expert troubleshooting and repair for malfunctioning electrical systems, including circuits, outlets, and breakers.",
      backgroundImage: "",
      features: ["Troubleshooting","Circuit repair","Outlet repair"],
    },
    {
      icon: "Zap",
      title: "Panel Upgrades",
      description: "Electrical panel replacement and upgrades to ensure your system runs safely and meets modern power demands.",
      backgroundImage: "",
      features: ["Panel replacement","Breaker upgrades","Meter can replacement"],
    },
    {
      icon: "Zap",
      title: "House Rewiring",
      description: "Complete home rewiring services for safety, code compliance, and expanding electrical capacity.",
      backgroundImage: "",
      features: ["Whole-home rewiring","Electrical grounding","Code compliance"],
    },
    {
      icon: "Wrench",
      title: "Surge Protection",
      description: "Installation of surge protectors to defend your home from lightning strikes and power surges.",
      backgroundImage: "",
      features: ["Whole-house surge protection","Lightning strike defense"],
    },
    {
      icon: "Wrench",
      title: "Lighting & Fixtures",
      description: "Installation and replacement of light fixtures, chandeliers, ceiling fans, and outdoor lighting.",
      backgroundImage: "",
      features: ["Chandelier installation","Ceiling fan installation","Outdoor lighting"],
    },
    {
      icon: "Zap",
      title: "Emergency Electrical Services",
      description: "24/7 rapid response for burning smells, sparking outlets, and other urgent electrical hazards.",
      backgroundImage: "",
      features: ["24/7 availability","Burning smell diagnosis","Sparking outlet repair"],
    },
    {
      icon: "ClipboardCheck",
      title: "Safety Inspection",
      description: "Thorough electrical inspections to verify system safety and prevent future issues.",
      backgroundImage: "",
      features: ["System verification","Hazard identification","Preventative maintenance"],
    },
    {
      icon: "Zap",
      title: "EV Charging Stations",
      description: "Professional installation of electric vehicle charging stations for your home.",
      backgroundImage: "",
      features: ["EV charger installation","Panel capacity assessment"],
    },
    {
      icon: "Zap",
      title: "Generator Installation",
      description: "Backup generator installation to keep your home powered during outages.",
      backgroundImage: "",
      features: ["Generator installation","Backup power solutions"],
    }
  ] as ServiceItem[],
  pricingTiers: [

  ] as PricingTier[],
  reviews: [

  ] as ReviewItem[],
  googleReviewAvg: 5.0,
  googleReviewCount: 50,
  galleryImages: [
    {
      src: "",
      alt: "Mister Sparky Electrical Repairs",
    },
    {
      src: "",
      alt: "Mister Sparky Panel Upgrades",
    },
    {
      src: "",
      alt: "Mister Sparky House Rewiring",
    }
  ] as GalleryImage[],
  guaranteeHeadline: "Miami's On-Time Electrician",
  guaranteeText: "We’re committed to repair work that fits your need for speed and reliability.",
  guaranteePoints: ["On-time service","Licensed and insured professionals","24/7 emergency availability"],
  serviceOptions: ["Breakers & Fuses", "Ceiling Fans", "Chandelier Installation", "Circuit Repair", "Commercial", "Electrical Grounding", "Safety Inspection", "Outlet Installation", "Outlet Repair", "Electrical Panel Replacement", "Electrical Repairs", "Troubleshooting", "Electrical Emergencies", "EV Charging Stations", "Generator Installation", "Light Fixture Installation", "Lightning Strikes", "Meter Can Replacement", "Outdoor Lighting", "Smoke Detectors", "Surge Protection", "House Rewiring"],
  formWebhookUrl: "https://hooks.zapier.com/hooks/catch/26623925/uj1eyis/",
  formSource: "miami-mister-sparky",
  badges: ["Licensed","Insured","24/7 Emergency Service Available"],
  footerYear: new Date().getFullYear(),
  footerLinks: {
    services: ["Electrical Repairs", "Panel Upgrades", "House Rewiring", "Surge Protection", "Lighting & Fixtures", "Emergency Electrical Services", "Safety Inspection", "EV Charging Stations", "Generator Installation"],
    company: [
      { label: 'About Us', href: '#about' },
      { label: 'Our Guarantee', href: '#guarantee' },
      { label: 'Reviews', href: '#reviews' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  socialLinks: {
    facebook: "",
    instagram: "",
    google: "https://miamimistersparky.com/",
  },
  buildMeta: {
    clientId: "miami-mister-sparky",
    companyName: "Mister Sparky",
    generatedAt: "2026-04-21T22:56:08.471Z",
    profileSchemaDate: "2026-04-20",
  } as BuildMeta,
};
